version: '3.0'
services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    env_file:
      - .development.env
    ports:
      - 5432:5432
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

volumes:
  pg-data:


